#!/usr/bin/env python3
"""Generate the readable programme documents from program.json.

    python3 tools/make-program-doc.py            (or: npm run docs)
    python3 tools/make-program-doc.py --check    exit 1 if any doc is stale

Writes three files, all committed so a normal checkout needs no tooling:

    docs/PROGRAM.md   the whole programme, swim and gym
    docs/SWIM.md      the swim half, standalone
    docs/GYM.md       the gym half, standalone

The two halves exist to be handed on their own - to a coach, or pasted into a
general-purpose LLM - so each opens with enough context (who the athlete is,
how the day is laid out) to be understood without the other.

The point of generating them is that the previous document - a hand-made PDF -
drifted a whole major version out of date because nothing tied it to the data.
Never hand-edit the output; edit program.json and re-run this.

Deliberately omitted: media.json video links, the `equipment` slugs and the
`priority` values. Those are app plumbing, not programme content.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "program.json"
DOCS = ROOT / "docs"


def cell(text) -> str:
    """A table cell: pipes would end the column early."""
    return str(text).replace("|", "\\|")


def rng(pair) -> str:
    """[1, 1] is "1", not "1-1"."""
    low, high = pair
    return str(low) if low == high else f"{low}-{high}"


def plural(count: str, word: str) -> str:
    return f"{count} {word}" if count == "1" else f"{count} {word}s"


def code_list(codes) -> str:
    """["A4", "B4", "C1"] -> "A4, B4 & C1", matching the app."""
    return codes[0] if len(codes) < 2 else f"{', '.join(codes[:-1])} & {codes[-1]}"


def meta(ex):
    """Same rule the app and the PDF use: tempo, else benefit, else grip."""
    for label, key in (("Tempo", "tempo"), ("Benefit", "benefit"), ("Grip", "grip")):
        if ex.get(key):
            return label, ex[key]
    return None, None


def table(header, rows):
    out = ["| " + " | ".join(header) + " |",
           "| " + " | ".join(["---"] * len(header)) + " |"]
    out += ["| " + " | ".join(cell(c) for c in row) + " |" for row in rows]
    return out


# ---------- shared context ----------

def header(data, title, about, subtitle=None):
    p = data["program"]
    return [
        "<!-- Generated by tools/make-program-doc.py from program.json. Do not edit by hand. -->",
        "",
        f"# {title} (v{p['version']})",
        "",
        f"*{subtitle or p['subtitle']}*",
        "",
        f"> {about} Programme version {p['version']}, last updated {p['updatedAt']}.",
    ]


def athlete(data):
    p = data["program"]
    a = p["athlete"]
    L = ["## The Athlete", "",
         f"- **Age:** {a['age']}",
         f"- **Primary sport:** {a['primarySport']}",
         f"- **Training goal:** {a['trainingGoal']}",
         f"- **Joint focus:** {a['jointFocus']}",
         ""]
    L += table([h["label"] for h in p["highlights"]],
               [[h["value"] for h in p["highlights"]]])
    return L


def protocol(data):
    L = ["## Daily Timing Protocol", ""]
    L += table(["Time Window", "Activity / Event", "Nutritional & Recovery Strategy"],
               [[r["timeWindow"], r["activity"], r["strategy"]] for r in data["dailyProtocol"]])
    return L


def fuel(data):
    f = data.get("fuel")
    if not f:
        return []
    return [f"## {f['title']} ({f['timeWindow']})", "",
            f"**Recipe:** {f['recipe']}", "", f"**Why:** {f['why']}"]


# ---------- swim ----------

def swim_section(swim):
    """Lengths and Express times are derived exactly as the app derives them."""
    pool = swim["poolMeters"]

    def dist(meters):
        return f"{meters:,}m / {meters // pool} lengths"

    def blocks(items):
        out = []
        for b in items:
            out += [f"- **{b['title']} ({dist(b['meters'])}):** {b['detail']}"]
            out += [f"    - {pt}" for pt in b.get("points", [])]
            if b.get("rest"):
                out += [f"    - *Rest: {b['rest']}*"]
        return out

    names = {r["id"]: r["name"] for r in swim["routines"]}
    L = [f"## {swim['title']}", "",
         f"*{swim['subtitle']}* - every session is {dist(swim['sessionMeters'])} "
         f"in a {pool}m pool, about {swim['sessionMinutes']} minutes with rests. "
         "The routine is fixed to the weekday.", "", "### Weekly Rotation", ""]
    L += table(["Day", "Routine", "Primary Training Objective"],
               [[r["day"], names[r["routineId"]], r["objective"]] for r in swim["schedule"]])

    for r in swim["routines"]:
        days = [row["day"] for row in swim["schedule"] if row["routineId"] == r["id"]]
        L += ["", f"### {r['name']} ({', '.join(days)})", "", f"*Target: {r['target']}*", ""]
        if r.get("rounds", 1) > 1:
            per_round = sum(b["meters"] for b in r["blocks"])
            L += [f"{r['rounds']} rounds of this {per_round:,}m block:", ""]
        L += blocks(r["blocks"])

    ex = swim.get("express")
    if ex:
        L += ["", f"### {ex['title']}", "", ex["intro"], ""]
        L += blocks([ex["warmUp"], ex["mainBlock"], ex["coolDown"]])
        L += ["", "**Time options** (estimated from the real pace, "
              f"{swim['sessionMeters']:,}m in {swim['sessionMinutes']} minutes, rests included):", ""]
        for i, opt in enumerate(ex["options"], 1):
            meters = ex["warmUp"]["meters"] + opt["mainBlocks"] * ex["mainBlock"]["meters"] + ex["coolDown"]["meters"]
            minutes = round(meters * swim["sessionMinutes"] / swim["sessionMeters"] / 5) * 5
            label = plural(str(opt["mainBlocks"]), "Main Block")
            L += [f"{i}. **About {minutes} min - {dist(meters)}:** Warm-Up + {label} + Cool-Down."]
        L += ["", f"*{ex['note']}*"]

    br, turn, missed = swim["breathing"], swim["openTurn"], swim["missedSessions"]
    L += ["", f"### {br['title']}", ""]
    L += [f"- **{pt['label']}:** {pt['text']}" for pt in br["points"]]
    L += ["", f"### {turn['title']}", "", turn["intro"], ""]
    L += table(["Step", "Phase", "Action & Biomechanical Cue"],
               [[i, s["phase"], s["action"]] for i, s in enumerate(turn["steps"], 1)])
    L += ["", f"### {missed['title']}", ""]
    L += [f"- **{pt['label']}:** {pt['text']}" for pt in missed["points"]]
    return L


# ---------- gym ----------

def bookends(data):
    warm, cool = data["warmUp"], data["coolDown"]
    duration = f" ({rng(warm['durationMinutes'])} mins)" if warm.get("durationMinutes") else ""
    pres = cool["prescription"]
    return ["## Warm-Up & Cool-Down", "",
            f"### {warm['title']}{duration}", "", warm["execution"], "",
            f"### {cool['title']}", "",
            f"- **Timing:** {cool['timing']}",
            f"- **Why:** {cool['why']}",
            f"- **How to do it:** {plural(rng(pres['sets']), 'set')} of "
            f"{rng(pres['durationSeconds'])} seconds. {pres['note']}"]


def rules(data):
    L = [f"## Rules of Training & Joint Safety (Age {data['program']['athlete']['age']})", ""]
    for i, rule in enumerate(data["rules"], 1):
        L += [f"**{i}. {rule['title']}**", "", rule["body"], ""]
    return L[:-1]


def legs(data):
    l = data.get("legTraining")
    return [f"## {l['title']}", "", l["body"]] if l else []


def sessions(data):
    L = ["## The Sessions", "",
         "Three sessions rotate in order - Day 1, Day 2, Day 3, then back to Day 1 - "
         "with roughly a two-day gap between gym mornings. Exercise codes (B1, A3...) "
         "are stable ids, not an order: the letter does not indicate the day."]
    by_code = {ex["code"]: ex for w in data["workouts"] for ex in w["exercises"]}
    for workout in data["workouts"]:
        L += ["", f"### {workout['name']}", "", f"*{workout['focus']}*"]
        for ex in workout["exercises"]:
            key = " **[Key Compound]**" if "key-compound" in ex.get("tags", []) else ""
            L += ["", f"**{ex['code']} - {ex['name']}**{key}", "",
                  f"- **Prescription:** {ex['prescription']}",
                  f"- **Target:** {ex['target']}"]
            label, value = meta(ex)
            if label:
                L += [f"- **{label}:** {value}"]
            if ex.get("logAs") in by_code:
                other = by_code[ex["logAs"]]
                day = next(w["name"].split(":")[0] for w in data["workouts"] if other in w["exercises"])
                L += [f"- **Same movement as {other['code']} ({day})** - progress carries over between the two."]
            L += ["- **Cues:**"]
            L += [f"    - {cue}" for cue in ex["cues"]]
    return L


def matrix(data):
    m = data["swappingMatrix"]
    L = ["## Equipment Availability & Exercise Swapping", "", f"> {m['anchorNote']}", ""]
    for i, tier in enumerate(m["tiers"], 1):
        L += [f"**{i}. {tier['label']}**", ""]
        L += [f"- **{code_list(item['codes'])}:** {item['note']}" for item in tier["items"]]
        L += [""]
    return L + [f"> **The Golden Rule:** {m['goldenRule']}"]


def schedule(data):
    L = ["## Example Week", "",
         "The swim routine is fixed to the weekday. The gym days are only an example: "
         "in practice Day 1, Day 2 and Day 3 rotate with roughly a two-day gap, so "
         "they drift across weekdays.", ""]
    return L + table(["Day", "Morning", "Afternoon", "Focus"],
                     [[d["day"], d["morning"], d["afternoon"], d["focus"]] for d in data["weeklySchedule"]])


def summary(data):
    return ["## Summary Strategy", "", data["summaryStrategy"]]


# ---------- documents ----------

def document(parts) -> str:
    """Sections separated by rules; empty sections (optional data) are skipped."""
    head, *rest = [part for part in parts if part]
    L = head
    for part in rest:
        L += ["", "---", ""] + part
    return "\n".join(L) + "\n"


def build(data):
    title = data["program"]["title"]
    swim = [swim_section(data["swim"])] if data.get("swim") else []
    gym = [bookends(data), rules(data), legs(data), sessions(data), matrix(data)]
    return {
        "PROGRAM.md": document([
            header(data, title,
                   "The complete programme: a daily fasted swim followed by a short gym session. "
                   "The same content is split into SWIM.md and GYM.md for handing on separately."),
            athlete(data), protocol(data), fuel(data), *swim, *gym, schedule(data), summary(data),
        ]),
        "SWIM.md": document([
            header(data, f"{title} - Swim Programme",
                   "The swim half of a personal programme that pairs a daily fasted swim with a "
                   "20-25 minute gym session straight afterwards. The gym half is in GYM.md.",
                   subtitle=f"{data['swim']['subtitle']} | Swimmer Program (Age {data['program']['athlete']['age']})"),
            athlete(data), protocol(data), *swim, fuel(data),
        ]),
        "GYM.md": document([
            header(data, f"{title} - Gym Programme",
                   "The gym half of a personal programme. Every gym session follows a 90-minute "
                   "fasted swim, which serves as its warm-up. The swim half is in SWIM.md."),
            athlete(data), protocol(data), fuel(data), *gym, schedule(data), summary(data),
        ]),
    }


def main():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    docs = build(data)

    # --check writes nothing: it fails when a committed doc no longer matches
    # program.json, which is what the pre-commit hook runs.
    if "--check" in sys.argv:
        stale = [name for name, text in docs.items()
                 if not (DOCS / name).exists() or (DOCS / name).read_text(encoding="utf-8") != text]
        for name in stale:
            print(f"out of date: docs/{name}", file=sys.stderr)
        sys.exit(1 if stale else 0)

    for name, text in docs.items():
        out = DOCS / name
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
