#!/usr/bin/env python3
"""Generate the readable programme document from program.json.

    python3 tools/make-program-doc.py

Writes docs/PROGRAM.md. Regenerate whenever program.json changes; the output is
committed so a normal checkout needs no tooling to read the programme.

The point of generating it is that the previous document - a hand-made PDF -
drifted a whole major version out of date because nothing tied it to the data.
Never hand-edit the output; edit program.json and re-run this.

Deliberately omitted: media.json video links, the `equipment` slugs and the
`priority` values. Those are app plumbing, not programme content.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "program.json"
OUT = ROOT / "docs" / "PROGRAM.md"


def cell(text) -> str:
    """A table cell: pipes would end the column early."""
    return str(text).replace("|", "\\|")


def rng(pair) -> str:
    """[1, 1] is "1", not "1-1"."""
    low, high = pair
    return str(low) if low == high else f"{low}-{high}"


def plural(count: str, word: str) -> str:
    return f"{count} {word}" if count == "1" else f"{count} {word}s"


def code_list(codes) -> str:
    """["A4", "B4", "C1"] -> "A4, B4 & C1", matching the app."""
    return codes[0] if len(codes) < 2 else f"{', '.join(codes[:-1])} & {codes[-1]}"


def meta(ex):
    """Same rule the app and the PDF use: tempo, else benefit, else grip."""
    for label, key in (("Tempo", "tempo"), ("Benefit", "benefit"), ("Grip", "grip")):
        if ex.get(key):
            return label, ex[key]
    return None, None


def table(header, rows):
    out = ["| " + " | ".join(header) + " |",
           "| " + " | ".join(["---"] * len(header)) + " |"]
    out += ["| " + " | ".join(cell(c) for c in row) + " |" for row in rows]
    return out


def swim_section(swim):
    """Lengths and Express times are derived exactly as the app derives them."""
    pool = swim["poolMeters"]

    def dist(meters):
        return f"{meters:,}m / {meters // pool} lengths"

    def blocks(items):
        out = []
        for b in items:
            out += [f"- **{b['title']} ({dist(b['meters'])}):** {b['detail']}"]
            out += [f"    - {pt}" for pt in b.get("points", [])]
            if b.get("rest"):
                out += [f"    - *Rest: {b['rest']}*"]
        return out

    names = {r["id"]: r["name"] for r in swim["routines"]}
    L = ["", "---", "", f"## {swim['title']}", "",
         f"*{swim['subtitle']}* - every session is {dist(swim['sessionMeters'])} "
         f"in a {pool}m pool, fixed to the weekday.", "", "### Weekly Rotation", ""]
    L += table(["Day", "Routine", "Primary Training Objective"],
               [[r["day"], names[r["routineId"]], r["objective"]] for r in swim["schedule"]])

    for r in swim["routines"]:
        days = [row["day"] for row in swim["schedule"] if row["routineId"] == r["id"]]
        L += ["", f"### {r['name']} ({', '.join(days)})", "", f"*Target: {r['target']}*", ""]
        if r.get("rounds", 1) > 1:
            per_round = sum(b["meters"] for b in r["blocks"])
            L += [f"{r['rounds']} rounds of this {per_round:,}m block:", ""]
        L += blocks(r["blocks"])

    ex = swim.get("express")
    if ex:
        L += ["", f"### {ex['title']}", "", ex["intro"], ""]
        L += blocks([ex["warmUp"], ex["mainBlock"], ex["coolDown"]])
        L += ["", "**Time options** (estimated from the real pace, "
              f"{swim['sessionMeters']:,}m in {swim['sessionMinutes']} minutes, rests included):", ""]
        for i, opt in enumerate(ex["options"], 1):
            meters = ex["warmUp"]["meters"] + opt["mainBlocks"] * ex["mainBlock"]["meters"] + ex["coolDown"]["meters"]
            minutes = round(meters * swim["sessionMinutes"] / swim["sessionMeters"] / 5) * 5
            label = plural(str(opt["mainBlocks"]), "Main Block")
            L += [f"{i}. **About {minutes} min - {dist(meters)}:** Warm-Up + {label} + Cool-Down."]
        L += ["", f"*{ex['note']}*"]

    br, turn, missed = swim["breathing"], swim["openTurn"], swim["missedSessions"]
    L += ["", f"### {br['title']}", ""]
    L += [f"- **{pt['label']}:** {pt['text']}" for pt in br["points"]]
    L += ["", f"### {turn['title']}", "", turn["intro"], ""]
    L += table(["Step", "Phase", "Action & Biomechanical Cue"],
               [[i, s["phase"], s["action"]] for i, s in enumerate(turn["steps"], 1)])
    L += ["", f"### {missed['title']}", ""]
    L += [f"- **{pt['label']}:** {pt['text']}" for pt in missed["points"]]
    return L


def build(data) -> str:
    p = data["program"]
    L = [
        "<!-- Generated by tools/make-program-doc.py from program.json. Do not edit by hand. -->",
        "",
        f"# {p['title']} (v{p['version']})",
        "",
        f"*{p['subtitle']}*",
        "",
        f"Last updated {p['updatedAt']}.",
        "",
    ]
    L += table([h["label"] for h in p["highlights"]],
               [[h["value"] for h in p["highlights"]]])

    L += ["", "---", "", "## Daily Timing Protocol", ""]
    L += table(["Time Window", "Activity / Event", "Nutritional & Recovery Strategy"],
               [[r["timeWindow"], r["activity"], r["strategy"]] for r in data["dailyProtocol"]])

    if fuel := data.get("fuel"):
        L += ["", "---", "", f"## {fuel['title']} ({fuel['timeWindow']})", "",
              f"**Recipe:** {fuel['recipe']}", "", f"**Why:** {fuel['why']}"]

    if swim := data.get("swim"):
        L += swim_section(swim)

    warm, cool = data["warmUp"], data["coolDown"]
    duration = f" ({rng(warm['durationMinutes'])} mins)" if warm.get("durationMinutes") else ""
    L += ["", "---", "", "## Warm-Up & Cool-Down", "",
          f"### {warm['title']}{duration}", "", warm["execution"], "",
          f"### {cool['title']}", "",
          f"- **Timing:** {cool['timing']}",
          f"- **Why:** {cool['why']}"]
    pres = cool["prescription"]
    L += [f"- **How to do it:** {plural(rng(pres['sets']), 'set')} of "
          f"{rng(pres['durationSeconds'])} seconds. {pres['note']}"]

    L += ["", "---", "", f"## Rules of Training & Joint Safety (Age {p['athlete']['age']})", ""]
    for i, rule in enumerate(data["rules"], 1):
        L += [f"**{i}. {rule['title']}**", "", rule["body"], ""]
    L = L[:-1]

    if legs := data.get("legTraining"):
        L += ["", "---", "", f"## {legs['title']}", "", legs["body"]]

    L += ["", "---", "", "## The Sessions", ""]
    for workout in data["workouts"]:
        L += [f"### {workout['name']}", "", f"*{workout['focus']}*", ""]
        for ex in workout["exercises"]:
            key = " **[Key Compound]**" if "key-compound" in ex.get("tags", []) else ""
            L += [f"**{ex['code']} - {ex['name']}**{key}", "",
                  f"- **Prescription:** {ex['prescription']}",
                  f"- **Target:** {ex['target']}"]
            label, value = meta(ex)
            if label:
                L += [f"- **{label}:** {value}"]
            L += ["- **Cues:**"]
            L += [f"    - {cue}" for cue in ex["cues"]]
            L += [""]

    matrix = data["swappingMatrix"]
    L += ["---", "", "## Equipment Availability & Exercise Swapping", "",
          f"> {matrix['anchorNote']}", ""]
    for i, tier in enumerate(matrix["tiers"], 1):
        L += [f"**{i}. {tier['label']}**", ""]
        L += [f"- **{code_list(item['codes'])}:** {item['note']}" for item in tier["items"]]
        L += [""]
    L += [f"> **The Golden Rule:** {matrix['goldenRule']}", ""]

    L += ["---", "", "## Weekly Schedule", ""]
    L += table(["Day", "Morning", "Afternoon", "Focus"],
               [[d["day"], d["morning"], d["afternoon"], d["focus"]] for d in data["weeklySchedule"]])

    L += ["", "---", "", "## Summary Strategy", "", data["summaryStrategy"], ""]
    return "\n".join(L)


def main():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    OUT.write_text(build(data), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
